# Generated by Django 4.1.1 on 2022-11-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cakes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tastes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameid', models.IntegerField(blank=True, null=True)),
                ('discription', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tastes',
                'managed': False,
            },
        ),
    ]
